[profile.default]
src = 'contracts'
out = 'out'
libs = ['seadrop/lib']
solc_version = '0.8.17'
remappings = [
    'openzeppelin-contracts/=seadrop/lib/openzeppelin-contracts/contracts',
    'ds-test/=seadrop/lib/forge-std/lib/ds-test/src/',
    'seadrop/=seadrop/src/',
    'yourproject/=contracts/'
]
optimizer_runs = 1_000_000
ignored_error_codes = []
bytecode_hash = "none"

[rpc_endpoints]
sepolia = '${SEPOLIA_RPC_URL}'
mainnet = '${ETHEREUM_RPC_URL}'